pub_hdrs = h{**}

./: $pub_hdrs

# Install into the MoltenVK/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/MoltenVK/
  install.subdirs = true
}
