pub_hdrs = {hxx ixx txx}{**}

./: $pub_hdrs

# Install into the MoltenVK/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/MoltenVK/
  install.subdirs = true
}
